import type { Ingredient, PackagingUnit } from "./types"

export const categorySymbols = {
  Essen: "🍔",
  "Getränke Pet": "💧",
  "Getränke Glas": "🥛",
  "Getränke Spezial": "⭐", // Changed from ☕ to ⭐
  Equipment: "🍳",
  Kassa: "💰",
  Einkaufen: "🛒",
  Produkte: "🛒", // Renamed from Einkaufen for Bestellung mode
}

export const categories = [
  "Essen",
  "Getränke Pet",
  "Getränke Glas",
  "Getränke Spezial",
  "Equipment",
  "Kassa",
  "Einkaufen",
] // Added new category

export const productsByCategory = {
  Essen: [
    "Backhendl Box Salat",
    "Backhendl Box Pommes",
    "Käsekrainer Box",
    "Schweinsbraten Box",
    "Zwiebelrostbraten Box",
    "Paprikahendl Box",
    "Schnitzel Box",
    "Backhendl Burger",
    "Prater Burger",
    "Hof Burger",
    "Schönbrunner Burger",
    "Veganes Backhendl Salat",
    "Veganes Backhendl Pommes",
    "Veggie Burger",
    "Veggie Box",
    "Falafel Box",
    "Vegan Wrap",
    "Käsespätzle",
    "Vienna Hotdog",
    "Sacherwürstel Klassisch",
    "Käsekrainer Klassisch",
    "Pommes Frites Teller",
    "Rohscheiben Box",
    "Warmer Schokokuchen",
    "Marilleneisknödel",
    "Kaiserschmarrn",
  ].sort(),

  "Getränke Pet": [
    "Wasser still",
    "Wasser prick",
    "Cola ZERO",
    "Cola",
    "Fanta/Schartnerbombe",
    "Apfelsaft gespritzt",
    "Sprite",
    "Eistee Pfi",
    "Eistee Zit",
    "Almdudler",
  ].sort(),

  "Getränke Glas": [
    "Wasser still",
    "Wasser prick",
    "Cola ZERO",
    "Cola",
    "Fanta/Schartnerbombe",
    "Apfelsaft gespritzt",
    "Sprite",
    "Eistee Pfi",
    "Eistee Zit",
    "Almdudler",
    "Bier",
    "Spritzer",
  ].sort(),

  // Update the Getränke Spezial products
  "Getränke Spezial": [
    "Becher",
    "Bierfass",
    "Gas",
    "Kaffee",
    "Kaffeekapsel",
    "Milch",
    "Punschkocher",
    "Zapfanlage",
  ].sort(),

  Equipment: [
    "Öl Kübel",
    "Fahne",
    "Fahnenständer",
    "Müllsack",
    "Handschuhe",
    "Öl",
    "Preissticker",
    "Seitenzettel",
    "Speisekarte",
    "Wasserkanister",
    "32A Kabel 25 Meter",
    "Desinfektionsmittel",
    "Fettlöser",
    "Küchenrolle á 8 Stück",
    "Zuckersieb mit Schüssel",
  ].sort(),

  Kassa: ["Bonrolle", "5 € Scheine", "2 € Rolle", "1 € Rolle", "50 Cent Rolle", "20 Cent Rolle", "10 Cent Rolle"],

  Einkaufen: [
    "Apfelmus",
    "Bratkartoffeln",
    "Burgerpatty",
    "Burgersauce",
    "Esterhazymix",
    "Falafel",
    "Hotdog Brot",
    "Hühnerschitzel",
    "Backhendlstreifen",
    "Hummus",
    "Kartoffelsalat",
    "Käse",
    "Käse gerieben",
    "Käsekrainer",
    "Kernöl",
    "Ketchup",
    "Kren",
    "Liebstöckl",
    "Marillenknödel",
    "Mayonnaise",
    "Muskat",
    "Obers",
    "Paprikawürfel",
    "Paprikagemüse",
    "Paprikahendl",
    "Pasta Nockerl",
    "Pommes Frites",
    "Praterstelze",
    "Preiselbeeren",
    "Rindfleisch",
    "Rohscheiben",
    "Röstzwiebeln",
    "rote Zwiebeln",
    "Sacherwürstel",
    "Salz",
    "Sauerkraut",
    "Schlagobers",
    "Schnittlauchsauce",
    "Nutella/Milka",
    "Schokokuchen",
    "Schwarzer Pfeffer",
    "Schweinsbraten",
    "Schweinskruspel",
    "Semmel",
    "Senf",
    "Serviettenknödel",
    "Staubzucker",
    "Tafelspitz",
    "Teig",
    "Vanillezucker",
    "Veganes Suppenpulver",
    "Veggielaibchen",
    "Vogerlsalat",
    "Wrap",
    "Zwieblersauce",
  ].sort(),

  // Renamed Einkaufen to Produkte for Bestellung mode
  Produkte: [
    "Apfelmus",
    "Bratkartoffeln",
    "Burgerpatty",
    "Burgersauce",
    "Esterhazymix",
    "Falafel",
    "Hotdog Brot",
    "Hühnerschitzel",
    "Backhendlstreifen",
    "Hummus",
    "Kartoffelsalat",
    "Käse",
    "Käse gerieben",
    "Käsekrainer",
    "Kernöl",
    "Ketchup",
    "Kren",
    "Liebstöckl",
    "Marillenknödel",
    "Mayonnaise",
    "Muskat",
    "Obers",
    "Paprikawürfel",
    "Paprikagemüse",
    "Paprikahendl",
    "Pasta Nockerl",
    "Pommes Frites",
    "Praterstelze",
    "Preiselbeeren",
    "Rindfleisch",
    "Rohscheiben",
    "Röstzwiebeln",
    "rote Zwiebeln",
    "Sacherwürstel",
    "Salz",
    "Sauerkraut",
    "Schlagobers",
    "Schnittlauchsauce",
    "Nutella/Milka",
    "Schokokuchen",
    "Schwarzer Pfeffer",
    "Schweinsbraten",
    "Schweinskruspel",
    "Semmel",
    "Senf",
    "Serviettenknödel",
    "Staubzucker",
    "Tafelspitz",
    "Teig",
    "Vanillezucker",
    "Veganes Suppenpulver",
    "Veggielaibchen",
    "Vogerlsalat",
    "Wrap",
    "Zwieblersauce",
  ].sort(),
}

export const unitPlurals = {
  Dose: "Dosen",
  Flasche: "Flaschen",
  Glas: "Gläser",
  Gramm: "Gramm",
  Karton: "Kartons",
  Kilogramm: "Kilogramm",
  Kiste: "Kisten",
  Kübel: "Kübeln",
  Liter: "Liter",
  Milliliter: "Milliliter",
  Paar: "Paare",
  Packung: "Packungen",
  Plastikschale: "Plastikschalen",
  Rolle: "Rollen",
  Sack: "Säcke",
  Sackerl: "Sackerln",
  Stück: "Stücke",
  Tray: "Trays",
  Tetrapack: "Tetrapacks",
  "Tricolor Packung": "Tricolor Packungen",
  Tupperware: "Tupperwares",
  Fass: "Fässer", // Added for Bierfass
  Anlage: "Anlagen", // Added for Zapfanlage
  Flasche: "Flaschen", // Added for Gas
}

export const productUnits = {
  Essen: [
    ["Backhendl Box Salat", "Stück"],
    ["Backhendl Box Pommes", "Stück"],
    ["Käsekrainer Box", "Stück"],
    ["Schweinsbraten Box", "Stück"],
    ["Zwiebelrostbraten Box", "Stück"],
    ["Paprikahendl Box", "Stück"],
    ["Schnitzel Box", "Stück"],
    ["Backhendl Burger", "Stück"],
    ["Prater Burger", "Stück"],
    ["Hof Burger", "Stück"],
    ["Schönbrunner Burger", "Stück"],
    ["Veganes Backhendl Salat", "Stück"],
    ["Veganes Backhendl Pommes", "Stück"],
    ["Veggie Burger", "Stück"],
    ["Veggie Box", "Stück"],
    ["Falafel Box", "Stück"],
    ["Vegan Wrap", "Stück"],
    ["Käsespätzle", "Stück"],
    ["Vienna Hotdog", "Stück"],
    ["Sacherwürstel Klassisch", "Stück"],
    ["Käsekrainer Klassisch", "Stück"],
    ["Pommes Frites Teller", "Stück"],
    ["Rohscheiben Box", "Stück"],
    ["Warmer Schokokuchen", "Stück"],
    ["Marilleneisknödel", "Stück"],
    ["Kaiserschmarrn", "Stück"],
  ],

  "Getränke Pet": [
    ["Wasser still", "Tray"],
    ["Wasser prick", "Tray"],
    ["Cola ZERO", "Tray"],
    ["Cola", "Tray"],
    ["Fanta/Schartnerbombe", "Tray"],
    ["Apfelsaft gespritzt", "Tray"],
    ["Sprite", "Tray"],
    ["Eistee Pfi", "Tray"],
    ["Eistee Zit", "Tray"],
    ["Almdudler", "Tray"],
  ],

  "Getränke Glas": [
    ["Wasser still", "Kiste"],
    ["Wasser prick", "Kiste"],
    ["Cola ZERO", "Kiste"],
    ["Cola", "Kiste"],
    ["Fanta/Schartnerbombe", "Kiste"],
    ["Apfelsaft gespritzt", "Kiste"],
    ["Sprite", "Kiste"],
    ["Eistee Pfi", "Kiste"],
    ["Eistee Zit", "Kiste"],
    ["Almdudler", "Kiste"],
    ["Bier", "Kiste"],
    ["Spritzer", "Kiste"],
  ],

  // Update the Getränke Spezial units (all Stück except Milch = Liter)
  "Getränke Spezial": [
    ["Becher", "Stück"],
    ["Bierfass", "Stück"],
    ["Gas", "Stück"],
    ["Kaffee", "Stück"],
    ["Kaffeekapsel", "Stück"],
    ["Milch", "Liter"],
    ["Punschkocher", "Stück"],
    ["Zapfanlage", "Stück"],
  ],

  Equipment: [
    ["Öl Kübel", "Stück"],
    ["Boxen", "Stück"],
    ["Fahne", "Stück"],
    ["Fahnenständer", "Stück"],
    ["Müllsack", "Rolle"],
    ["Handschuhe", "Packung"],
    ["Öl", "Stück"],
    ["Preissticker", "Stück"],
    ["Seitenzettel", "Stück"],
    ["Speisekarte", "Stück"],
    ["Wasserkanister", "Stück"],
    ["32A Kabel 25 Meter", "Stück"],
    ["Desinfektionsmittel", "Stück"],
    ["Fettlöser", "Stück"],
    ["Küchenrolle á 8 Stück", "Packung"],
    ["Zuckersieb mit Schüssel", "Stück"],
  ],

  Kassa: [
    ["Bonrolle", "Stück"],
    ["5 € Scheine", "Stück"],
    ["2 € Rolle", "Rolle"],
    ["1 € Rolle", "Rolle"],
    ["50 Cent Rolle", "Rolle"],
    ["20 Cent Rolle", "Rolle"],
    ["10 Cent Rolle", "Rolle"],
  ],

  Einkaufen: [
    ["Apfelmus", "Glas"],
    ["Bratkartoffeln", "Karton"],
    ["Burgerpatty", "Karton"],
    ["Burgersauce", "Kübel"],
    ["Esterhazymix", "Plastikschale"],
    ["Falafel", "Sackerl"],
    ["Hotdog Brot", "Kiste"],
    ["Hühnerschitzel", "Sack"],
    ["Backhendlstreifen", "Sack"],
    ["Hummus", "Kübel"],
    ["Kartoffelsalat", "Kübel"],
    ["Käse", "Plastikschale"],
    ["Käse gerieben", "Sackerl"],
    ["Käsekrainer", "Sackerl"],
    ["Kernöl", "Flasche"],
    ["Ketchup", "Kübel"],
    ["Kren", "Kübel"],
    ["Liebstöckl", "Dose"],
    ["Marillenknödel", "Packung"],
    ["Mayonnaise", "Kübel"],
    ["Muskat", "Packung"],
    ["Obers", "Tetrapack"],
    ["Paprikawürfel", "Tricolor Packung"],
    ["Paprikagemüse", "Tricolor Packung"],
    ["Paprikahendl", "Tupperware"],
    ["Pasta Nockerl", "Sackerl"],
    ["Pommes Frites", "Karton"],
    ["Praterstelze", "Tupperware"],
    ["Preiselbeeren", "Dose"],
    ["Rindfleisch", "Sack"],
    ["Rohscheiben", "Kiste"],
    ["Röstzwiebeln", "Sack"],
    ["rote Zwiebeln", "Sack"],
    ["Sacherwürstel", "Paar"],
    ["Salz", "Sack"],
    ["Sauerkraut", "Dose"],
    ["Schlagobers", "Packung"],
    ["Schnittlauchsauce", "Tupperware"],
    ["Nutella/Milka", "Glas"],
    ["Schokokuchen", "Karton"],
    ["Schwarzer Pfeffer", "Sack"],
    ["Schweinsbraten", "Sack"],
    ["Schweinskruspel", "Sack"],
    ["Semmel", "Kiste"],
    ["Senf", "Kübel"],
    ["Serviettenknödel", "Karton"],
    ["Staubzucker", "Packung"],
    ["Tafelspitz", "Tupperware"],
    ["Teig", "Kübel"],
    ["Vanillezucker", "Packung"],
    ["Veganes Suppenpulver", "Dose"],
    ["Veggielaibchen", "Sackerl"],
    ["Vogerlsalat", "Karton"],
    ["Wrap", "Sackerl"],
    ["Zwieblersauce", "Tupperware"],
  ],

  // Add Produkte category with the same units as Einkaufen
  Produkte: [
    ["Apfelmus", "Glas"],
    ["Bratkartoffeln", "Karton"],
    ["Burgerpatty", "Karton"],
    ["Burgersauce", "Kübel"],
    ["Esterhazymix", "Plastikschale"],
    ["Falafel", "Sackerl"],
    ["Hotdog Brot", "Kiste"],
    ["Hühnerschitzel", "Sack"],
    ["Backhendlstreifen", "Sack"],
    ["Hummus", "Kübel"],
    ["Kartoffelsalat", "Kübel"],
    ["Käse", "Plastikschale"],
    ["Käse gerieben", "Sackerl"],
    ["Käsekrainer", "Sackerl"],
    ["Kernöl", "Flasche"],
    ["Ketchup", "Kübel"],
    ["Kren", "Kübel"],
    ["Liebstöckl", "Dose"],
    ["Marillenknödel", "Packung"],
    ["Mayonnaise", "Kübel"],
    ["Muskat", "Packung"],
    ["Obers", "Tetrapack"],
    ["Paprikawürfel", "Tricolor Packung"],
    ["Paprikagemüse", "Tricolor Packung"],
    ["Paprikahendl", "Tupperware"],
    ["Pasta Nockerl", "Sackerl"],
    ["Pommes Frites", "Karton"],
    ["Praterstelze", "Tupperware"],
    ["Preiselbeeren", "Dose"],
    ["Rindfleisch", "Sack"],
    ["Rohscheiben", "Kiste"],
    ["Röstzwiebeln", "Sack"],
    ["rote Zwiebeln", "Sack"],
    ["Sacherwürstel", "Paar"],
    ["Salz", "Sack"],
    ["Sauerkraut", "Dose"],
    ["Schlagobers", "Packung"],
    ["Schnittlauchsauce", "Tupperware"],
    ["Nutella/Milka", "Glas"],
    ["Schokokuchen", "Karton"],
    ["Schwarzer Pfeffer", "Sack"],
    ["Schweinsbraten", "Sack"],
    ["Schweinskruspel", "Sack"],
    ["Semmel", "Kiste"],
    ["Senf", "Kübel"],
    ["Serviettenknödel", "Karton"],
    ["Staubzucker", "Packung"],
    ["Tafelspitz", "Tupperware"],
    ["Teig", "Kübel"],
    ["Vanillezucker", "Packung"],
    ["Veganes Suppenpulver", "Dose"],
    ["Veggielaibchen", "Sackerl"],
    ["Vogerlsalat", "Karton"],
    ["Wrap", "Sackerl"],
    ["Zwieblersauce", "Tupperware"],
  ],
}

// Recipe data
export const recipes: Record<string, Record<string, Ingredient>> = {
  "Backhendl Box Salat": {
    Backhendlstreifen: { menge: 150, einheit: "Gramm" },
    Vogerlsalat: { menge: 50, einheit: "Gramm" },
    Kartoffelsalat: { menge: 200, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Backhendl Box Pommes": {
    Backhendlstreifen: { menge: 150, einheit: "Gramm" },
    "Pommes Frites": { menge: 250, einheit: "Gramm" },
    Ketchup: { menge: 30, einheit: "Gramm" },
    Mayonnaise: { menge: 30, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Käsekrainer Box": {
    Käsekrainer: { menge: 1, einheit: "Stück" },
    "Pommes Frites": { menge: 250, einheit: "Gramm" },
    Ketchup: { menge: 30, einheit: "Gramm" },
    Senf: { menge: 30, einheit: "Gramm" },
    Kren: { menge: 10, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Schweinsbraten Box": {
    Schweinsbraten: { menge: 150, einheit: "Gramm" },
    Schweinskruspel: { menge: 20, einheit: "Gramm" },
    Serviettenknödel: { menge: 120, einheit: "Gramm" },
    Sauerkraut: { menge: 100, einheit: "Gramm" },
    Kren: { menge: 10, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Zwiebelrostbraten Box": {
    Rindfleisch: { menge: 150, einheit: "Gramm" },
    Zwieblersauce: { menge: 120, einheit: "Gramm" },
    Bratkartoffeln: { menge: 200, einheit: "Gramm" },
    Röstzwiebeln: { menge: 30, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Paprikahendl Box": {
    Paprikahendl: { menge: 150, einheit: "Gramm" },
    "Pasta Nockerl": { menge: 200, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Schnitzel Box": {
    Hühnerschitzel: { menge: 150, einheit: "Gramm" },
    "Pommes Frites": { menge: 250, einheit: "Gramm" },
    Ketchup: { menge: 30, einheit: "Gramm" },
    Mayonnaise: { menge: 30, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Backhendl Burger": {
    Backhendlstreifen: { menge: 100, einheit: "Gramm" },
    Semmel: { menge: 1, einheit: "Stück" },
    Burgersauce: { menge: 30, einheit: "Gramm" },
    Vogerlsalat: { menge: 20, einheit: "Gramm" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Prater Burger": {
    Burgerpatty: { menge: 1, einheit: "Stück" },
    Semmel: { menge: 1, einheit: "Stück" },
    Burgersauce: { menge: 30, einheit: "Gramm" },
    Käse: { menge: 1, einheit: "Stück" },
    "rote Zwiebeln": { menge: 20, einheit: "Gramm" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Hof Burger": {
    Burgerpatty: { menge: 1, einheit: "Stück" },
    Semmel: { menge: 1, einheit: "Stück" },
    Burgersauce: { menge: 30, einheit: "Gramm" },
    Käse: { menge: 1, einheit: "Stück" },
    Röstzwiebeln: { menge: 20, einheit: "Gramm" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Schönbrunner Burger": {
    Burgerpatty: { menge: 1, einheit: "Stück" },
    Semmel: { menge: 1, einheit: "Stück" },
    Burgersauce: { menge: 30, einheit: "Gramm" },
    Käse: { menge: 1, einheit: "Stück" },
    Preiselbeeren: { menge: 20, einheit: "Gramm" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Veganes Backhendl Salat": {
    "Veganes Backhendl": { menge: 150, einheit: "Gramm" },
    Vogerlsalat: { menge: 50, einheit: "Gramm" },
    Kartoffelsalat: { menge: 200, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Veganes Backhendl Pommes": {
    "Veganes Backhendl": { menge: 150, einheit: "Gramm" },
    "Pommes Frites": { menge: 250, einheit: "Gramm" },
    Ketchup: { menge: 30, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Veggie Burger": {
    Veggielaibchen: { menge: 1, einheit: "Stück" },
    Semmel: { menge: 1, einheit: "Stück" },
    Hummus: { menge: 30, einheit: "Gramm" },
    Vogerlsalat: { menge: 20, einheit: "Gramm" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Veggie Box": {
    Veggielaibchen: { menge: 2, einheit: "Stück" },
    Hummus: { menge: 50, einheit: "Gramm" },
    Vogerlsalat: { menge: 50, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Falafel Box": {
    Falafel: { menge: 150, einheit: "Gramm" },
    Hummus: { menge: 50, einheit: "Gramm" },
    Vogerlsalat: { menge: 50, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Vegan Wrap": {
    Wrap: { menge: 1, einheit: "Stück" },
    Falafel: { menge: 100, einheit: "Gramm" },
    Hummus: { menge: 30, einheit: "Gramm" },
    Vogerlsalat: { menge: 30, einheit: "Gramm" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  Käsespätzle: {
    "Pasta Nockerl": { menge: 200, einheit: "Gramm" },
    "Käse gerieben": { menge: 50, einheit: "Gramm" },
    Röstzwiebeln: { menge: 20, einheit: "Gramm" },
    Box: { menge: 1.5, einheit: "Stück" },
    Gabel: { menge: 1.5, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Vienna Hotdog": {
    "Hotdog Brot": { menge: 1, einheit: "Stück" },
    Sacherwürstel: { menge: 1, einheit: "Paar" },
    Ketchup: { menge: 20, einheit: "Gramm" },
    Senf: { menge: 20, einheit: "Gramm" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Sacherwürstel Klassisch": {
    Sacherwürstel: { menge: 1, einheit: "Paar" },
    Senf: { menge: 20, einheit: "Gramm" },
    Kren: { menge: 10, einheit: "Gramm" },
    Box: { menge: 1, einheit: "Stück" },
    Gabel: { menge: 1, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Käsekrainer Klassisch": {
    Käsekrainer: { menge: 1, einheit: "Stück" },
    Senf: { menge: 20, einheit: "Gramm" },
    Kren: { menge: 10, einheit: "Gramm" },
    Box: { menge: 1, einheit: "Stück" },
    Gabel: { menge: 1, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Pommes Frites Teller": {
    "Pommes Frites": { menge: 300, einheit: "Gramm" },
    Ketchup: { menge: 30, einheit: "Gramm" },
    Mayonnaise: { menge: 30, einheit: "Gramm" },
    Box: { menge: 1, einheit: "Stück" },
    Gabel: { menge: 1, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Rohscheiben Box": {
    Rohscheiben: { menge: 200, einheit: "Gramm" },
    Ketchup: { menge: 30, einheit: "Gramm" },
    Box: { menge: 1, einheit: "Stück" },
    Gabel: { menge: 1, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  "Warmer Schokokuchen": {
    Schokokuchen: { menge: 1, einheit: "Stück" },
    Schlagobers: { menge: 30, einheit: "Milliliter" },
    Box: { menge: 1, einheit: "Stück" },
    Eislöffel: { menge: 1, einheit: "Stück" },
    Servietten: { menge: 1, einheit: "Stück" },
  },

  Marilleneisknödel: {
    Marillenknödel: { menge: 2, einheit: "Stück" },
    Schlagobers: { menge: 30, einheit: "Milliliter" },
    Eisbecher: { menge: 1, einheit: "Stück" },
    Eislöffel: { menge: 1, einheit: "Stück" },
    Servietten: { menge: 1, einheit: "Stück" },
  },

  Kaiserschmarrn: {
    Teig: { menge: 200, einheit: "Gramm" },
    Apfelmus: { menge: 50, einheit: "Gramm" },
    Staubzucker: { menge: 10, einheit: "Gramm" },
    Box: { menge: 1, einheit: "Stück" },
    Gabel: { menge: 1, einheit: "Stück" },
    Servietten: { menge: 2, einheit: "Stück" },
  },

  // Empty recipes for Getränke Pet products
  "Wasser still": {},
  "Wasser prick": {},
  "Cola ZERO": {},
  Cola: {},
  "Fanta/Schartnerbombe": {},
  "Apfelsaft gespritzt": {},
  Sprite: {},
  "Eistee Pfi": {},
  "Eistee Zit": {},
  Almdudler: {},
  Bier: {},
  Spritzer: {},

  // Empty recipes for Getränke Spezial products
  Becher: {},
  Bierfass: {},
  Gas: {},
  Kaffee: {},
  Kaffeekapsel: {},
  Milch: {},
  Punschkocher: {},
  Zapfanlage: {},

  // Add default recipes for equipment
  "Öl Kübel": {
    "Öl Kübel": { menge: 1, einheit: "Stück" },
  },
  Fahne: {
    Fahne: { menge: 1, einheit: "Stück" },
  },
  Fahnenständer: {
    Fahnenständer: { menge: 1, einheit: "Stück" },
  },
  Müllsack: {
    Müllsack: { menge: 1, einheit: "Rolle" },
  },
  Handschuhe: {
    Handschuhe: { menge: 1, einheit: "Packung" },
  },
  Öl: {
    Öl: { menge: 1, einheit: "Stück" },
  },
  Preissticker: {
    Preissticker: { menge: 1, einheit: "Stück" },
  },
  Seitenzettel: {
    Seitenzettel: { menge: 1, einheit: "Stück" },
  },
  Speisekarte: {
    Speisekarte: { menge: 1, einheit: "Stück" },
  },
  Wasserkanister: {
    Wasserkanister: { menge: 1, einheit: "Stück" },
  },
  "32A Kabel 25 Meter": {
    "32A Kabel 25 Meter": { menge: 1, einheit: "Stück" },
  },
  Desinfektionsmittel: {
    Desinfektionsmittel: { menge: 1, einheit: "Stück" },
  },
  Fettlöser: {
    Fettlöser: { menge: 1, einheit: "Stück" },
  },
  "Küchenrolle á 8 Stück": {
    "Küchenrolle á 8 Stück": { menge: 1, einheit: "Packung" },
  },
  "Zuckersieb mit Schüssel": {
    "Zuckersieb mit Schüssel": { menge: 1, einheit: "Stück" },
  },

  // Add default recipes for Kassa items
  Bonrolle: {
    Bonrolle: { menge: 1, einheit: "Stück" },
  },
  "5 € Scheine": {
    "5 € Scheine": { menge: 1, einheit: "Stück" },
  },
  "2 € Rolle": {
    "2 € Rolle": { menge: 1, einheit: "Rolle" },
  },
  "1 € Rolle": {
    "1 € Rolle": { menge: 1, einheit: "Rolle" },
  },
  "50 Cent Rolle": {
    "50 Cent Rolle": { menge: 1, einheit: "Rolle" },
  },
  "20 Cent Rolle": {
    "20 Cent Rolle": { menge: 1, einheit: "Rolle" },
  },
  "10 Cent Rolle": {
    "10 Cent Rolle": { menge: 1, einheit: "Rolle" },
  },
}

// Function to parse weight
export function parseWeight(value: string): number {
  value = value.trim().toLowerCase()

  if (value.includes("kg")) {
    const kgValue = Number.parseFloat(value.replace("kg", "").trim())
    return Math.round(kgValue * 1000)
  } else if (value.includes("g")) {
    const gValue = Number.parseFloat(value.replace("g", "").trim())
    return Math.round(gValue)
  } else if (value.includes("l")) {
    const lValue = Number.parseFloat(value.replace("l", "").trim())
    return Math.round(lValue * 1000)
  } else if (value.includes("ml")) {
    const mlValue = Number.parseFloat(value.replace("ml", "").trim())
    return Math.round(mlValue)
  } else {
    throw new Error(`Invalid input: ${value}. Please use 'g', 'kg', 'ml', or 'l'.`)
  }
}

// Packaging units
export const packagingUnits: Record<string, PackagingUnit> = {
  Apfelmus: { einheit: "Gramm", pro_verpackung: parseWeight("480 g"), verpackungseinheit: "Glas" },
  Bratkartoffeln: { einheit: "Gramm", pro_verpackung: parseWeight("10 kg"), verpackungseinheit: "Karton" },
  Burgerpatty: { einheit: "Stück", pro_verpackung: 28, verpackungseinheit: "Karton" },
  Burgersauce: { einheit: "Gramm", pro_verpackung: parseWeight("9 kg"), verpackungseinheit: "Kübel" },
  Box: { einheit: "Stück", pro_verpackung: 500, verpackungseinheit: "Karton" },
  Eisbecher: { einheit: "Stück", pro_verpackung: 200, verpackungseinheit: "Packung" },
  Esterhazymix: { einheit: "Gramm", pro_verpackung: parseWeight("1 kg"), verpackungseinheit: "Plastikschale" },
  Falafel: { einheit: "Gramm", pro_verpackung: parseWeight("1 kg"), verpackungseinheit: "Sackerl" },
  Gabel: { einheit: "Stück", pro_verpackung: 100, verpackungseinheit: "Sackerl" },
  "Hotdog Brot": { einheit: "Stück", pro_verpackung: 20, verpackungseinheit: "Kiste" },
  Hühnerschitzel: { einheit: "Gramm", pro_verpackung: parseWeight("3 kg"), verpackungseinheit: "Sack" },
  Backhendlstreifen: { einheit: "Gramm", pro_verpackung: parseWeight("3 kg"), verpackungseinheit: "Sack" },
  Hummus: { einheit: "Gramm", pro_verpackung: parseWeight("10 kg"), verpackungseinheit: "Kübel" },
  Kartoffelsalat: { einheit: "Gramm", pro_verpackung: parseWeight("10 kg"), verpackungseinheit: "Kübel" },
  Käse: { einheit: "Stück", pro_verpackung: 50, verpackungseinheit: "Plastikschale" },
  "Käse gerieben": { einheit: "Gramm", pro_verpackung: parseWeight("1 kg"), verpackungseinheit: "Sackerl" },
  Käsekrainer: { einheit: "Stück", pro_verpackung: 10, verpackungseinheit: "Sackerl" },
  Kernöl: { einheit: "Milliliter", pro_verpackung: parseWeight("1 l"), verpackungseinheit: "Flasche" },
  Ketchup: { einheit: "Gramm", pro_verpackung: parseWeight("10 kg"), verpackungseinheit: "Kübel" },
  Kren: { einheit: "Gramm", pro_verpackung: parseWeight("1 kg"), verpackungseinheit: "Kübel" },
  Liebstöckl: { einheit: "Gramm", pro_verpackung: parseWeight("200 g"), verpackungseinheit: "Dose" },
  Eislöffel: { einheit: "Stück", pro_verpackung: 100, verpackungseinheit: "Sackerl" },
  Marillenknödel: { einheit: "Stück", pro_verpackung: 6, verpackungseinheit: "Packung" },
  Mayonnaise: { einheit: "Gramm", pro_verpackung: parseWeight("10 kg"), verpackungseinheit: "Kübel" },
  Muskat: { einheit: "Gramm", pro_verpackung: parseWeight("100 g"), verpackungseinheit: "Packung" },
  "Nutella/Milka": { einheit: "Gramm", pro_verpackung: parseWeight("500 g"), verpackungseinheit: "Glas" },
  Obers: { einheit: "Milliliter", pro_verpackung: parseWeight("1 l"), verpackungseinheit: "Tetrapack" },
  Paprikawürfel: { einheit: "Gramm", pro_verpackung: parseWeight("500 g"), verpackungseinheit: "Tricolor Packung" },
  Paprikagemüse: { einheit: "Gramm", pro_verpackung: parseWeight("500 g"), verpackungseinheit: "Tricolor Packung" },
  Paprikahendl: { einheit: "Gramm", pro_verpackung: parseWeight("5 kg"), verpackungseinheit: "Tupperware" },
  "Pasta Nockerl": { einheit: "Gramm", pro_verpackung: parseWeight("2.5 kg"), verpackungseinheit: "Sackerl" },
  "Pommes Frites": { einheit: "Gramm", pro_verpackung: parseWeight("10 kg"), verpackungseinheit: "Karton" },
  Pommesgabeln: { einheit: "Stück", pro_verpackung: 1000, verpackungseinheit: "Karton" },
  Praterstelze: { einheit: "Gramm", pro_verpackung: parseWeight("700 g"), verpackungseinheit: "Tupperware" },
  Preiselbeeren: { einheit: "Gramm", pro_verpackung: parseWeight("5 kg"), verpackungseinheit: "Dose" },
  Rindfleisch: { einheit: "Gramm", pro_verpackung: parseWeight("1 kg"), verpackungseinheit: "Sack" },
  Rohscheiben: { einheit: "Gramm", pro_verpackung: parseWeight("2 kg"), verpackungseinheit: "Kiste" },
  Röstzwiebeln: { einheit: "Gramm", pro_verpackung: parseWeight("2 kg"), verpackungseinheit: "Sack" },
  "rote Zwiebeln": { einheit: "Gramm", pro_verpackung: parseWeight("5 kg"), verpackungseinheit: "Sack" },
  Sacherwürstel: { einheit: "Paar", pro_verpackung: 7, verpackungseinheit: "Sack" },
  Salz: { einheit: "Gramm", pro_verpackung: parseWeight("1 kg"), verpackungseinheit: "Sack" },
  Saucenbecher: { einheit: "Stück", pro_verpackung: 250, verpackungseinheit: "Sackerl" },
  Sauerkraut: { einheit: "Gramm", pro_verpackung: parseWeight("800 g"), verpackungseinheit: "Dose" },
  Schlagobers: { einheit: "Milliliter", pro_verpackung: parseWeight("1 l"), verpackungseinheit: "Packung" },
  Schnittlauchsauce: { einheit: "Gramm", pro_verpackung: parseWeight("800 g"), verpackungseinheit: "Tupperware" },
  Schokokuchen: { einheit: "Stück", pro_verpackung: 20, verpackungseinheit: "Karton" },
  "Schwarzer Pfeffer": { einheit: "Gramm", pro_verpackung: parseWeight("1 kg"), verpackungseinheit: "Sack" },
  Schweinsbraten: { einheit: "Gramm", pro_verpackung: parseWeight("3 kg"), verpackungseinheit: "Sack" },
  Schweinskruspel: { einheit: "Gramm", pro_verpackung: parseWeight("500 g"), verpackungseinheit: "Sack" },
  Semmel: { einheit: "Stück", pro_verpackung: 50, verpackungseinheit: "Kiste" },
  Senf: { einheit: "Gramm", pro_verpackung: parseWeight("10 kg"), verpackungseinheit: "Kübel" },
  Servietten: { einheit: "Stück", pro_verpackung: 2500, verpackungseinheit: "Karton" },
  Serviettenknödel: { einheit: "Gramm", pro_verpackung: parseWeight("1.5 kg"), verpackungseinheit: "Karton" },
  Staubzucker: { einheit: "Gramm", pro_verpackung: parseWeight("500 g"), verpackungseinheit: "Packung" },
  Tafelspitz: { einheit: "Gramm", pro_verpackung: parseWeight("600 g"), verpackungseinheit: "Tupperware" },
  Teig: { einheit: "Gramm", pro_verpackung: parseWeight("9 kg"), verpackungseinheit: "Kübel" },
  Teller: { einheit: "Stück", pro_verpackung: 600, verpackungseinheit: "Karton" },
  Vanillezucker: { einheit: "Gramm", pro_verpackung: parseWeight("500 g"), verpackungseinheit: "Packung" },
  "Veganes Suppenpulver": { einheit: "Gramm", pro_verpackung: parseWeight("1 kg"), verpackungseinheit: "Dose" },
  Veggielaibchen: { einheit: "Gramm", pro_verpackung: parseWeight("2 kg"), verpackungseinheit: "Sackerl" },
  "Veganes Backhendl": { einheit: "Gramm", pro_verpackung: parseWeight("5 kg"), verpackungseinheit: "Sackerl" },
  Vogerlsalat: { einheit: "Gramm", pro_verpackung: parseWeight("800 g"), verpackungseinheit: "Karton" },
  Wrap: { einheit: "Stück", pro_verpackung: 18, verpackungseinheit: "Sackerl" },
  Zwieblersauce: { einheit: "Gramm", pro_verpackung: parseWeight("5 kg"), verpackungseinheit: "Tupperware" },

  // Add packaging units for new Getränke Spezial items
  Becher: { einheit: "Stück", pro_verpackung: 100, verpackungseinheit: "Packung" },
  Bierfass: { einheit: "Liter", pro_verpackung: 30, verpackungseinheit: "Fass" },
  Gas: { einheit: "Stück", pro_verpackung: 1, verpackungseinheit: "Flasche" },
  Kaffee: { einheit: "Gramm", pro_verpackung: parseWeight("500 g"), verpackungseinheit: "Packung" },
  Kaffeekapsel: { einheit: "Stück", pro_verpackung: 50, verpackungseinheit: "Packung" },
  Milch: { einheit: "Milliliter", pro_verpackung: parseWeight("1 l"), verpackungseinheit: "Tetrapack" },
  Punschkocher: { einheit: "Stück", pro_verpackung: 1, verpackungseinheit: "Stück" },
  Zapfanlage: { einheit: "Stück", pro_verpackung: 1, verpackungseinheit: "Anlage" },
}
